---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  labels:
    name: mongodb-deploy
    app: profile-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-pod
      app: profile-app
  template:
    metadata:
      name: mongodb-pod
      labels:
        name: mongodb-pod
        app: profile-app
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
