---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress
  labels:
    name: mongoexpress-service
    app: profile-app
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    name: mongoexpress-pod
    app: profile-app